### ISSUE TITLE
Attaching files ?

### ISSUE THREAD

**Issue by AdityaSher** [jamiewilson/form-to-google-sheets#28]
Is it possible to attach files ?

**Comment by Doomd** [comment]
>Is it possible to attach files ?

@AdityaSher Your question is probably too broad to answer specifically without guessing what you mean. Attach files (FROM WHERE) & (TO WHAT)? Can one upload a file to a web server with a web form? Yes. That’s been possible since last century...If you know what you’re doing. Can one upload a file to your web server and then have a google apps script move, process, and store that into say Google Drive or Google Cloud Storage? Yes. That’s also possible. Here’s an article that discusses one way to do that (which you can adapt for your needs probably:

https://www.labnol.org/code/19747-google-forms-upload-files/

And some documentation to get you started:
https://developers.google.com/apps-script/advanced/drive

And StackDriver has a few answers: https://stackoverflow.com/questions/15670392/uploading-file-using-google-apps-script-using-htmlservice

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by AdityaSher** [comment]
> Is it possible to attach files ?
I am sorry for being unclear.

here is my problem 
Is is possile to attach a file on a static webpage hosted on gtihub pages ? (files directly get uploaded to a google form ? ) is that possible?
